[project]
name = "aiexperiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.12.0",
    "huggingface-hub>=1.4.1",
    "numpy>=2.4.2",
    "torch>=2.10.0",
    "transformers>=5.1.0",
]
